env:
  browser: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
rules:
  indent:
    - error
    - 2
    - SwitchCase: 2
      ArrayExpression: off
  semi:
    - error
    - always
